# Generated by Django 5.1.1 on 2024-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_at', models.DateTimeField()),
                ('headcount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirm'), ('CC', 'Canceled'), ('NS', 'No Show')], default='PD')),
            ],
        ),
    ]
